In [2]:
from HTorch import HTensor, HParameter
from HTorch.manifolds import Euclidean, PoincareBall, Lorentz, HalfSpace, Sphere
import torch

In [22]:
cur = torch.tensor(-1.2)
cur = torch.nn.Parameter(cur)

In [28]:
a = HTensor([[0.2, 0.3, 0.1],[0.2, 0.3, 0.1]], curvature=cur)
print(a, a.curvature)

Hyperbolic tensor([[0.2000, 0.3000, 0.1000],
        [0.2000, 0.3000, 0.1000]]), manifold=PoincareBall, curvature=-1.2000000476837158 Parameter containing:
tensor(-1.2000, requires_grad=True)


In [31]:
a[0].expmap

<bound method HTensor.expmap of Hyperbolic tensor([0.2000, 0.3000, 0.1000]), manifold=PoincareBall, curvature=-1.2000000476837158>

In [24]:
u = HParameter(a)
print(u)
print(u.curvature)

Hyperbolic Parameter containing:
tensor([0.2000, 0.3000, 0.1000], requires_grad=True), manifold=PoincareBall, curvature=-1.2000000476837158
Parameter containing:
tensor(-1.2000, requires_grad=True)


In [25]:
loss = u.sum() + cur
print(loss)
loss.backward()

tensor(-0.6000, grad_fn=<AddBackward0>)


In [26]:
cur.grad

tensor(1.)

In [27]:
u.grad

tensor([1., 1., 1.])

In [2]:
a = HTensor([0.2, 0.3, 0.1], manifold='PoincareBall')
b = HTensor([0.2, 0.3, 0.1], manifold='HalfSpace')
ori = HTensor([0.0,0.0, 0.0], manifold='PoincareBall')

In [3]:
u = HParameter(a, )
print(u)
print(u.curvature)

Hyperbolic Parameter containing:
Parameter(HParameter([0.2000, 0.3000, 0.1000], requires_grad=True)), manifold=PoincareBall, curvature=-1.0
-1.0


In [4]:
loss = u.Hdist(ori)
print(loss)

tensor(0.7865, grad_fn=<AliasBackward0>)


In [5]:
loss.backward()

In [6]:
u.grad

tensor([1.2431, 1.8646, 0.6215])

In [7]:
u.curvature

-1.0

### check sphere 

In [8]:
a = HTensor([0.2, 0.3, 0.1], manifold='Sphere', curvature=1.0)
b = HTensor([0.1, 0.2, 0.1], manifold='Sphere', curvature=1.0)

In [10]:
a.check_(), b.check_()

(tensor(False), tensor(False))

In [13]:
print(a, b)
a.check_(), b.check_()

Hyperbolic HTensor([0.5345, 0.8018, 0.2673]), manifold=Sphere, curvature=1.0 Hyperbolic HTensor([0.4082, 0.8165, 0.4082]), manifold=Sphere, curvature=1.0


(tensor(True), tensor(True))

In [14]:
u = HParameter(a)
print(u)
print(u.curvature)

Hyperbolic Parameter containing:
Parameter(HParameter([0.5345, 0.8018, 0.2673], requires_grad=True)), manifold=Sphere, curvature=1.0
1.0


In [15]:
loss = u.Hdist(b)
print(loss)

tensor(0.1901, grad_fn=<AliasBackward0>)


In [16]:
loss.backward()

In [17]:
u.grad

tensor([-2.1602, -4.3205, -2.1602])