In [1]:
import sys
sys.path.append("..")
import torch
from HTorch import HTensor, HParameter, RiemannianSGD, RiemannianAdam

In [2]:
a = HTensor([0.2, 0.3, 0.1], manifold='PoincareBall')
b = HTensor([0.2, 0.3, 0.1], manifold='HalfSpace')
ori = HTensor([0.0,0.0, 0.0], manifold='PoincareBall')
v = torch.tensor([0.02, 0.01, 0.001])

### Test RiemannianSGD optimizer, sparse Hparameters to be test

In [3]:
u = HParameter(a)
print(u)
u_par =  [{'params': u,}]
optim = RiemannianSGD(u_par, lr=0.1, weight_decay=0.0)

Hyperbolic Parameter containing:
tensor([0.2000, 0.3000, 0.1000], requires_grad=True), manifold=PoincareBall, curvature=-1.0


In [4]:
optim.zero_grad()
loss = u.Hdist(ori)
print(loss)
loss.backward()
print(u.grad)
optim.step()
print(u, u.Hdist(ori))

tensor(0.7865, grad_fn=<AliasBackward0>)
tensor([1.2431, 1.8646, 0.6215])
Hyperbolic Parameter containing:
tensor([0.1766, 0.2649, 0.0883], requires_grad=True), manifold=PoincareBall, curvature=-1.0 tensor(0.6865, grad_fn=<AliasBackward0>)


### Test RiemannianAdam optimizer, sparse Hparameters to be test

In [5]:
u = HParameter(a)
print(u)
u_par =  [{'params': u,}]
optim = RiemannianAdam(u_par, lr=0.1, weight_decay=0.0)

Hyperbolic Parameter containing:
tensor([0.2000, 0.3000, 0.1000], requires_grad=True), manifold=PoincareBall, curvature=-1.0


In [6]:
optim.zero_grad()
loss = u.Hdist(ori)
print(loss)
loss.backward()
print(u.grad)
optim.step()
print(u, u.Hdist(ori))

tensor(0.7865, grad_fn=<AliasBackward0>)
tensor([1.2431, 1.8646, 0.6215])
Hyperbolic Parameter containing:
tensor([0.1766, 0.2649, 0.0883], requires_grad=True), manifold=PoincareBall, curvature=-1.0 tensor(0.6865, grad_fn=<AliasBackward0>)
